### ISSUE TITLE
Reporte de Practica 6 Equipo Mana

### ISSUE THREAD

**Issue by Arlet04** [SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipomana#1]
[Reporte de Practica 6 Equipo Mana.pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-proceso-de-negocio-en-bizagi-proyecto-equipomana/files/12811884/Reporte.de.Practica.6.Equipo.Mana.pdf)

**Comment by yanet02** [comment]
Calificación Final: **20/20**

_EXCELENTE TRABAJO_ 
Tiene una presentación muy buena y comprendible.
Cumple con todo lo requierido

**Comment by josealfredo79** [comment]
Bien hecho y revisado..
